#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update && sudo apt-get install nginx -y
sudo echo "Hello World!" > index.html
sudo cp index.html /var/www/html/index.nginx-debian.html
sudo service nginx restart