#!/usr/bin/env bash
#Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School

i="1"

while [ $i -lt 11 ]
do 
	if [ "$i" -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
i="$((i+1))"
done
