#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
a="1"
while [ $a -le 10 ]
do
if [ $a == "4" ]
then
echo "bad luck"
elif [ $a == "8" ]
then
echo "good luck"
else 
echo "Best School"
fi
a="$((a+1))"
done
