#!/bin/bash
chmod u+x *


# Check if a commit message is provided
if [ -z "$1" ]; then
  echo "Please provide a commit message."
  exit 1
fi

# Store the commit message
commit_message=$1

# Add all changes to the staging area
git add .

# Commit with the provided message
git commit -m "$commit_message"

# Push changes to the remote repository
git push

# Output a success message
echo "Changes have been pushed successfully."
